# Some notes:
#
# - Make sure we have either `node`, `npm` or `esy` invocations here as they
#   work both on linux/macos and windows.

steps:
  - script: 'npm install -g esy@0.5.0 --unsafe-perm'
    displayName: 'npm install -g esy'

  - script: 'npm install'
    displayName: 'npm install'

  - script: 'esy install'
    displayName: 'esy install'

  - script: 'esy build'
    displayName: 'esy build'

  - script: 'esy dune build @fmt'
    displayName: 'Check code formatting'

  - script: 'node scripts/bootstrap.js'
    displayName: 'esy bootstrap'

  - script: 'esy b dune runtest test'
    displayName: 'esy b dune runtest test'

  - script: 'node ./node_modules/jest-cli/bin/jest.js'
    displayName: 'esy test:e2e'

  - script: 'npm install'
    workingDirectory: './test-e2e-re/lib/verdaccio/'
    continueOnError: true
    displayName: 'esy test:e2e-re: npm install'

  - script: 'esy test:e2e-re'
    continueOnError: true
    displayName: 'esy test:e2e-re'

  - script: 'node ./test-e2e-slow/run-slow-tests.js'
    displayName: 'esy test:e2e-slow'

  - script: 'node ./scripts/make-platform-release.js'
    condition: succeededOrFailed()
    displayName: 'esy platform-release'
